### PR TITLE
Fix blob batch persistence

### LINKED ISSUE #363: Partition becomes unresponsive because event batch blob was deleted prematurely
We are seeing that partitions are unable to start because an eh-batch file was missing. 

At the time that these messages were logged the DurableTaskPartitions table showed that partition 8 failed to start (stuck outbox messages in all other partitions, timestamp multiple hours old).

FASTER state and the eventhub checkpoint data could be inconsistent/divergent because the eventhub checkpoint data is in separate blobs ({TaskHub Guid}/eh-checkpoints/). Since the Eventhubs Processor Library used by Netherite has (at least in some version) the possibility to Provide custom checkpoint data persistence, the data could be persisted in FASTER along with the other state data.

```
2024-03-01T14:15:51.502 [Error] EventHubsProcessor partitions/8 failed to read blob eh-batches/2024-03-01T09:32:29.2095178Z-588D70E4 for #278806: Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
2024-03-01T14:15:51.504 [Information] @processexecutor@000005: Executing '@processexecutor@000005' orchestration logic
2024-03-01T14:15:51.508 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=8e152620-b431-41b1-81d7-0711dad8734e)
2024-03-01T14:15:51.508 [Information] @processexecutor@000005: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (162288 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 8. TaskEventId: -1
2024-03-01T14:15:51.509 [Information] @processexecutor@000012: Executing '@processexecutor@000012' orchestration logic
2024-03-01T14:15:51.510 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=efb37fe7-d10c-4240-87bb-cdedf38b9df2)
2024-03-01T14:15:51.510 [Information] @processexecutor@000012: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (209644 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 9. TaskEventId: -1
2024-03-01T14:15:51.510 [Information] @processexecutor@000009: Executing '@processexecutor@000009' orchestration logic
2024-03-01T14:15:51.511 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=422c2408-eefe-44fa-828b-004c6361e2c1)
2024-03-01T14:15:51.511 [Information] @processexecutor@000009: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (130604 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 10. TaskEventId: -1
2024-03-01T14:15:51.618 [Information] Enter Business Partner Search Data Service
2024-03-01T14:15:51.620 [Trace] Batch Size Business Partner Search Data adjusted.
2024-03-01T14:15:51.620 [Trace] Mapping Business Partner Search Data
2024-03-01T14:15:51.620 [Trace] Mapping Business Partner Search Data
2024-03-01T14:15:51.714 [Error] EventHubsProcessor partitions/8(1) encountered an exception while processing packets : Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
2024-03-01T14:15:51.723 [Error] Part08 !!! Encountered exception while processing events in IEventProcessor.ProcessEventsAsync: Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435 terminatePartition=True
2024-03-01T14:15:51.753 [Information] Part08 Terminated partition after 581.00ms
```

### PR DESCRIPTION
**Pull request by sebastianburckhardt**
Fixes #363.

Previously, the code determined whether it was safe to delete a blob batch by checking the last update event for persistence. However, since there could still be read events after the update event, it meant that the blob may be deleted too early (and then hit a missing blob exception when trying to fetch the blob). This was observed in #363.

A similar mechanism was also used to determine whether a batch needed to be kept around for redelivery when reincarnating a partition. This has the same problems: a batch could be removed from the redelivery queue too early.

This PR fixes and simplifies this problem by
a) precisely tracking the persistence state of a batch by using the full position tuple (seqno, batchpos) in the redelivery queue, as opposed to only using the seqno. Read events can thus stay in the queue until later write events commit.
b) delete the blobs from storage at the same time we remove the batch from the redelivery queue.

### CODE REVIEW

**Comment by sebastianburckhardt** [comment]
I am still running more stress tests but it looks like the latest version of this now fixes the problem.

File: src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs [hunk 1]
```diff
@@ -47,9 +48,16 @@ class EventHubsProcessor : IEventProcessor, TransportAbstraction.IDurabilityList
...
         // we make this a concurrent queue so we can remove confirmed events concurrently with receiving new ones
-        readonly ConcurrentQueue<(PartitionEvent[] events, long offset, long seqno)> pendingDelivery;
+        readonly ConcurrentQueue<EventEntry> pendingDelivery;
         AsyncLock deliveryLock;
 
+        record struct EventEntry(long SeqNo, long BatchPos, PartitionEvent Event, bool LastInBatch, long Offset, BlockBlobClient BatchBlob)
+        {
+            public EventEntry(long seqNo, long batchPos, PartitionEvent evt) : this(seqNo, batchPos, evt, false, 0, null) { }
+
+            public EventEntry(long seqNo, long batchPos, PartitionEvent evt, long offset, BlockBlobClient blob) : this(seqNo, batchPos, evt, true, 0, blob) { }
```
Comment (davidmrdavid) [inline src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:58]: same feedback here about, in the future, specifying the param names for these "inline data" parameter, so we know what they represent :-)

File: src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs [hunk 2]
```diff
@@ -428,59 +453,54 @@ async Task IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumera
...
                                 evt.NextInputQueuePosition = seqNo;
                                 evt.NextInputQueueBatchPosition = i + 1;
+                                this.pendingDelivery.Enqueue(new EventEntry(seqNo, i, evt));
                             }
                             else
                             {
                                 evt.NextInputQueuePosition = seqNo + 1;
+                                evt.NextInputQueueBatchPosition = 0;
+                                this.pendingDelivery.Enqueue(new EventEntry(seqNo, i, evt, long.Parse(eventData.SystemProperties.Offset), blob));
                             }
```
Comment (davidmrdavid) [inline src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:482]: what scenarios do these two cases (the if and the else) represent? Trying to understand how they're distinct, as well as why we didn't have this enqueue'ing in the past.

**Review by davidmrdavid — COMMENTED** [review]
Left some questions

File: src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs [hunk 3]
```diff
@@ -125,6 +121,11 @@ public BlobBatchReceiver(string traceContext, EventHubsTraceHelper traceHelper,
                         // normal during shutdown
                         throw;
                     }
+                    catch (Azure.RequestFailedException exception) when (BlobUtilsV12.BlobDoesNotExist(exception) && errorHandler?.IsTerminated == true)
+                    {
+                        // a download can fail if the lease is lost and the next owner processes and then deletes it first
+                        throw new OperationCanceledException("blob already deleted", exception, token);
```
[the remark this answers is not in the document]
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:127]: Good point. I am updating the error message to be a bit more clear.

File: src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs [hunk 4]
```diff
@@ -141,6 +142,13 @@ public BlobBatchReceiver(string traceContext, EventHubsTraceHelper traceHelper,
                         var offset = i == 0 ? 0 : blobReference.PacketOffsets[i - 1];
                         var nextOffset = i < blobReference.PacketOffsets.Count ? blobReference.PacketOffsets[i] : blobContent.Length;
                         var length = nextOffset - offset;
+
+                        if (nextPacketToReceive?.BatchPos > i)
+                        {
+                            this.lowestTraceLevel?.LogTrace("{context} skipped over event #({seqno},{subSeqNo}) because it is already processed", this.traceContext, seqno, i);
+                            continue;
+                        }
```
[the remark this answers is not in the document]
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:150]: This case is about skipping *some but not all* of the events in the blob batch. The case where the entire blob batch is skipped is on line 60.

File: src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs (hunk 2 above)
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:482]: The point of the pendingDelivery queue was originally just to redeliver events to new incarnations of a partition if necessary. However, I am now also using it to manage the lifecycle of blob batches.

Stuff gets removed from that queue when a partition has persisted the delivery of an event. Originally I was storing entire batches in that queue. But it turned out that manage the lifecycle of these "pending delivery" events at the batch level does not work well (and I had several bugs in that code) because tracking when an event gets persisted depends on the type of event (read vs update), so now this is being tracked at the individual event level.

So instead of adding the entire batch to this queue (line 460 of the original file) we are now adding individual events (snippet above). The two clauses deal with the difference between an event in the middle of the batch, and the last event of the batch.

File: src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs [hunk 5]
```diff
@@ -122,17 +130,34 @@ Task IEventProcessor.OpenAsync(PartitionContext context)
...
-                if (this.pendingDelivery.TryDequeue(out var candidate))
+                if (this.pendingDelivery.TryDequeue(out var confirmed))
                 {
-                    this.persistedOffset = Math.Max(this.persistedOffset, candidate.offset);
-                    this.persistedSequenceNumber = Math.Max(this.persistedSequenceNumber, candidate.seqno);
+                    Debug.Assert(front == confirmed);
+                    if (confirmed.LastInBatch)
+                    {
+                        this.persistedOffset = Math.Max(this.persistedOffset, confirmed.Offset);
+                        this.persistedSequenceNumber = Math.Max(this.persistedSequenceNumber, confirmed.SeqNo);
```
[the remark this answers is not in the document]
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:156]: added a comment.

File: src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs [hunk 6]
```diff
@@ -428,59 +453,57 @@ async Task IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumera
...
                             if (i < events.Length - 1)
                             {
                                 evt.NextInputQueuePosition = seqNo;
                                 evt.NextInputQueueBatchPosition = i + 1;
+                                this.pendingDelivery.Enqueue(new EventEntry(seqNo, i, evt));
                             }
                             else
                             {
                                 evt.NextInputQueuePosition = seqNo + 1;
+                                evt.NextInputQueueBatchPosition = 0;
```
[the remark this answers is not in the document]
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs]: I have added those comments (slightly paraphrased)

File: src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs [hunk 7]
```diff
@@ -140,10 +140,16 @@ public BlobBatchReceiver(string traceContext, EventHubsTraceHelper traceHelper,
...
                     }
 
-                    TEvent[] result = new TEvent[blobReference.PacketOffsets.Count + 1];
+                    if (ignoreBatch)
+                    {
+                        this.traceHelper.LogWarning("{context} blob {blobName} for batch #{seqno} was not found. Ignoring batch since it must have been already delivered.", this.traceContext, blobClient.Name, seqno);
 
-                    if (!skipEntireBatch)
+                        yield return (eventData, new TEvent[0], seqno, null);
+                    }
```
Comment (davidmrdavid) [inline src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:148]: What does this return value represent? Especially confused about this `TEvent[0]`

**Review by davidmrdavid — COMMENTED** [review]
Just a quick question

File: src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs (hunk 7 above)
Comment (sebastianburckhardt) [reply src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:148]: it is an empty batch... no events should be processed

File: src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs [hunk 8]
```diff
@@ -135,56 +140,51 @@ public BlobBatchReceiver(string traceContext, EventHubsTraceHelper traceHelper,
...
-                    // we issue a deletion task; there is no strong guarantee that deletion will successfully complete
-                    // which means some blobs can be left behind temporarily.
-                    // This is fine because we have a second deletion path, a scan that removes old 
-                    // blobs that are past EH's expiration date.
+                        this.traceHelper.LogWarning("{context} blob {blobName} for batch #{seqno} was not found. Ignoring batch since it must have been already delivered.", this.traceContext, blobClient.Name, seqno);
 
-                    if (!this.keepUntilConfirmed)
-                    {
-                        var bgTask = Task.Run(() => this.DeleteBlobAsync(new BlockBlobClient[1] { blobClient }));
+                        yield return (eventData, new TEvent[0], seqno, null);
```
Comment (davidmrdavid) [inline src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:147]:
```suggestion
                        // return an empty batch, no events should be processed 
                        yield return (eventData, new TEvent[0], seqno, null);
```

**Review by davidmrdavid — APPROVED** [review]
